repos:
-   repo: local
    hooks:
    -   id: tsc
        name: tsc
        entry: tsc
        language: node
        always_run: true
        pass_filenames: false
        additional_dependencies: [typescript]
